import Head from "next/head";
import Layout from "../components/layouts/Layout";

export default function Home ()
{
 
  return (
   
    <div>
      <Head>
        <title>Pizzaria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* body */ }
      <main>
       <h1>Olá</h1>
      </main>
    </div>
  );
}

